# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20160628_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='geight_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
