# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160628_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='geight_field',
            new_name='height_field',
        ),
    ]
