# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20160628_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.ImageField(default=datetime.datetime(2016, 6, 28, 21, 5, 57, 477989, tzinfo=utc), upload_to='photo'),
            preserve_default=False,
        ),
    ]
