# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20160628_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.ImageField(upload_to=''),
        ),
    ]
