# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20160628_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='upload',
            new_name='photo',
        ),
    ]
