# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_information', models.TextField(max_length=300)),
                ('first_location', models.CharField(max_length=50)),
                ('second_location', models.CharField(max_length=50)),
                ('first_phone', models.CharField(max_length=15)),
                ('second_phone', models.CharField(max_length=15)),
                ('schelude', models.CharField(max_length=20)),
                ('advantages', models.CharField(max_length=50)),
            ],
        ),
    ]
