# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='advantages',
            field=models.TextField(max_length=100),
        ),
    ]
