# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20160617_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='schelude',
            new_name='schedule',
        ),
    ]
