# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_auto_20160617_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='schedule',
        ),
        migrations.AddField(
            model_name='about',
            name='schedule_first',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='schedule_second',
            field=models.CharField(default=228, max_length=40),
            preserve_default=False,
        ),
    ]
