# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
