# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 21, 18, 57, 27, 36878, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
